name: test_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  go_router: ^14.4.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  dartz: ^0.10.1
  record: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
